# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataanalysis.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dataAnalysis(object):
    def setupUi(self, dataAnalysis):
        dataAnalysis.setObjectName("dataAnalysis")
        dataAnalysis.resize(812, 728)
        self.centralwidget = QtWidgets.QWidget(dataAnalysis)
        self.centralwidget.setObjectName("centralwidget")
        self.pb_groupSelect = QtWidgets.QPushButton(self.centralwidget)
        self.pb_groupSelect.setGeometry(QtCore.QRect(380, 80, 151, 41))
        self.pb_groupSelect.setObjectName("pb_groupSelect")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 80, 211, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_data = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_data.setObjectName("pb_data")
        self.horizontalLayout.addWidget(self.pb_data)
        self.le_data = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_data.setObjectName("le_data")
        self.horizontalLayout.addWidget(self.le_data)
        self.pb_save = QtWidgets.QPushButton(self.centralwidget)
        self.pb_save.setGeometry(QtCore.QRect(630, 120, 151, 41))
        self.pb_save.setObjectName("pb_save")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 170, 781, 481))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tw_same = QtWidgets.QTableWidget(self.layoutWidget_2)
        self.tw_same.setObjectName("tw_same")
        self.tw_same.setColumnCount(0)
        self.tw_same.setRowCount(0)
        self.verticalLayout.addWidget(self.tw_same)
        self.tw_diff = QtWidgets.QTableWidget(self.layoutWidget_2)
        self.tw_diff.setObjectName("tw_diff")
        self.tw_diff.setColumnCount(0)
        self.tw_diff.setRowCount(0)
        self.verticalLayout.addWidget(self.tw_diff)
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(380, 0, 151, 61))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rb_match = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.rb_match.setObjectName("rb_match")
        self.verticalLayout_2.addWidget(self.rb_match)
        self.rb_mismatch = QtWidgets.QRadioButton(self.layoutWidget_3)
        self.rb_mismatch.setObjectName("rb_mismatch")
        self.verticalLayout_2.addWidget(self.rb_mismatch)
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 0, 211, 71))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget_4)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.te_specialAllele = QtWidgets.QTextEdit(self.layoutWidget_4)
        self.te_specialAllele.setObjectName("te_specialAllele")
        self.verticalLayout_3.addWidget(self.te_specialAllele)
        dataAnalysis.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(dataAnalysis)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 31))
        self.menubar.setObjectName("menubar")
        dataAnalysis.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(dataAnalysis)
        self.statusbar.setObjectName("statusbar")
        dataAnalysis.setStatusBar(self.statusbar)
        self.actionOpenFile = QtWidgets.QAction(dataAnalysis)
        self.actionOpenFile.setObjectName("actionOpenFile")

        self.retranslateUi(dataAnalysis)
        QtCore.QMetaObject.connectSlotsByName(dataAnalysis)

    def retranslateUi(self, dataAnalysis):
        _translate = QtCore.QCoreApplication.translate
        dataAnalysis.setWindowTitle(_translate("dataAnalysis", "MainWindow"))
        self.pb_groupSelect.setText(_translate("dataAnalysis", "groupSelect"))
        self.pb_data.setText(_translate("dataAnalysis", "data"))
        self.pb_save.setText(_translate("dataAnalysis", "save"))
        self.rb_match.setText(_translate("dataAnalysis", "match"))
        self.rb_mismatch.setText(_translate("dataAnalysis", "mismatch"))
        self.label.setText(_translate("dataAnalysis", "special allele"))
        self.actionOpenFile.setText(_translate("dataAnalysis", "openFile"))

